In [1]:
import tensorflow as tf

In [3]:
Scalar = tf.constant([2])
Vector = tf.constant([5,6,2])
Matrix = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
Tensor = tf.constant([
                        [[1,2,3],[2,3,4],[3,4,5]],
                        [[4,5,6],[5,6,7],[6,7,8]]
                    ])

In [4]:
with tf.Session() as session:
    print "Scalar:\n%s\n"%session.run(Scalar)
    print "Vector:\n%s\n"%session.run(Vector)
    print "Matrix:\n%s\n"%session.run(Matrix)
    print "Tensor:\n%s\n"%session.run(Tensor)

Scalar:
[2]

Vector:
[5 6 2]

Matrix:
[[1 2 3]
 [2 3 4]
 [3 4 5]]

Tensor:
[[[1 2 3]
  [2 3 4]
  [3 4 5]]

 [[4 5 6]
  [5 6 7]
  [6 7 8]]]



In [8]:
with tf.Session() as session:
    print "Scalar:\n%s\n"%session.run( tf.add(Scalar,Scalar))
    print "Vector:\n%s\n"%session.run( tf.add(Vector,Vector))
    print "Matrix:\n%s\n"%session.run( tf.add(Matrix,Matrix))
    print "Tensor:\n%s\n"%session.run( tf.add(Tensor,Tensor))

Scalar:
[4]

Vector:
[10 12  4]

Matrix:
[[ 2  4  6]
 [ 4  6  8]
 [ 6  8 10]]

Tensor:
[[[ 2  4  6]
  [ 4  6  8]
  [ 6  8 10]]

 [[ 8 10 12]
  [10 12 14]
  [12 14 16]]]



In [9]:
with tf.Session() as session:
    print session.run( tf.matmul(Matrix,Matrix))

[[14 20 26]
 [20 29 38]
 [26 38 50]]
