In [1]:
import numpy as np
x=[-1,2]#reverse order
h=[1,2,3,4]
print np.convolve(x,h,"same")#prefix zero padding
print np.convolve(x,h,"full")#postfix zero padding
print np.convolve(x,h,"valid")#no zero padding

[-1  0  1  2]
[-1  0  1  2  8]
[0 1 2]
